### ISSUE TITLE
STS document with sub-part element processing

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/sts2mn#33]
Source: https://github.com/metanorma/mn-samples-bsi/issues/2
Example:
https://github.com/metanorma/mn-samples-bsi/blob/master/reference-docs/pas/pas-2035/

STS Source XML has complex structure with sub-part:
```xml
<standard>
	<front>
            <nat-meta> </nat-meta> <!-- bibdata for 1st document -->
            <sec>Foreword, Introduction ....</sec> <!--  for 1st document -->
	</front>
	<body>
		<sub-part>
                        <body></body><back></back> <!-- Sections for 1st document -->
                </sub-part>
		<sub-part>
			<body>
				<sec id="sec_sp-Foreword">....</sec> <!-- Foreword, Introduction sections for 2nd document -->
				<sec id="sec_sp-Introduction">...</sec>
				<sub-part>
                                        <!-- Sections for 2nd document -->
					<body>Scope..... </body>
					<back>...</back>
				</sub-part>
			</body>
		</sub-part>
	</body>
</standard>
```

Conversion to MN XML: 
- source xml with sub-part elements should be converted to mn xml with the structure
```xml
<metanorma-collection ..>
    <doc-container id="...">
    </doc-container>
    <doc-container id="...">
    </doc-container>
</metanorma-collection>
```
i.e. for each `sub-part` should be created own `doc-container`.

Question for further analyses - the source data for 2nd document bibdata.

**Comment by Intelligent2013** [comment]
To do, experiment: for adoc output, try to generate similar structure like for BIPM brochure:
- https://github.com/metanorma/bipm-si-brochure/blob/master/sources/si-brochure-en.adoc
- https://github.com/metanorma/bipm-si-brochure/blob/master/sources/si-brochure-fr.adoc

pas-combined.yml
```yaml
directives:
  - documents-inline
bibdata:
  title:
    - language: en
      content: First document
    - language: en
      content: Second document
  type: collection
  docid:
    type: bipm
    id: sibrochure
  edition: 1
  date:
    - type: updated
      value: 2021-01-01
  copyright:
    owner:
      name: BSI
      abbreviation: BSI
    from: 2019
manifest:
  level: brochure
  title: Brochure/Brochure
  docref:
    - fileref: site/documents/doc1-en.xml
      identifier: doc1-en
    - fileref: site/documents/doc2-en.xml
      identifier: doc2-en
prefatory-content:
|


final-content:
|
```


and run command like this
```
metanorma collection pas-combined.yml -x xml,html,presentation,pdf  -w bilingual-brochure 
```

See BIPM Brochure: https://github.com/metanorma/bipm-si-brochure/
